version: '3'
services:
  local:
    build: .
    ports:
      - 10080:80
      - 10443:443
    volumes:
      - ./htdocs:/usr/local/apache2/htdocs/
      - ./etc/httpd/conf.d/ssl.conf:/etc/httpd/conf.d/ssl.conf
      - ./certs:/certs
